In [6]:
import numpy as np
x=np.array([1,2,3,4,5,6,7,8,9,10])
starr=x.reshape(2,5)
print(starr)
#even number any value 
#odd number only one value

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [16]:
x=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
carr=x.reshape(4,3,1)
print(carr)


[[[ 1]
  [ 2]
  [ 3]]

 [[ 4]
  [ 5]
  [ 6]]

 [[ 7]
  [ 8]
  [ 9]]

 [[10]
  [11]
  [12]]]


In [18]:
#hw 
#is numpy is 2d or 3d
#change prime or even

In [4]:
import numpy as np
x=np.array([[1,2,3,4,5],[6,7,8,9,10]])
y=np.array([[11,12,13,14,15],[16,17,18,19,20]])
addition = x+ y         
subtraction = x- y 
print("Addition:", addition)
print("Subtraction:", subtraction)

Addition: [[12 14 16 18 20]
 [22 24 26 28 30]]
Subtraction: [[-10 -10 -10 -10 -10]
 [-10 -10 -10 -10 -10]]


In [2]:
import numpy as np
a=np.array([5])
if a%2==0:
    print("Even")
else:
    print("Odd")

Odd
