In [1]:
import numpy

In [2]:
a=numpy.array(1)
print(a)

1


In [3]:
print(type(a))

<class 'numpy.ndarray'>


In [4]:
import numpy as np
print(np.__version__)

2.1.3


In [5]:
import numpy as np
a=np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [6]:
import numpy as np
a=np.array(100)
print(a.ndim)

0


In [9]:
import numpy as np
b=np.array([[1,2,3,4,5],[6,7,8,9,0]])
print(b.ndim)

2


In [16]:
import numpy as np
d=np.array([[[0,1,2,3],[4,5,6,7],[8,9,10,11],[12,13,14,15]]])
print(d)
print(d.ndim)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]]]
3


In [23]:
l=[[1,3],[5,9,],[3,4,5]]
l[2][1]

4